name 'gitbucket-supervisor'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures gitbucket-supervisor'
long_description 'Installs/Configures gitbucket-supervisor'
version '0.1.0'
depends 'supervisor'
depends 'java'
